### PR TITLE
Create Harshit_dwivedi.md

### PR DESCRIPTION
**Pull request by the-dagger**
test

### CODE REVIEW

**Comment by the-dagger** [comment]
Pliz merge gud sire @championswimmer

**Comment by Roshanjossey** [comment]
Hey @the-dagger , I'm working on a similar project to help first time open source contributors to get started with their first pull request.

Do check it out https://github.com/Roshanjossey/first-contributions

**Comment by the-dagger** [comment]
;_;

**Comment by championswimmer** [comment]
bro

**Pull request closed without merging**
